language: ruby
rvm:
  - 2.1.5

bundler_args: --without production

# env:
#   - TESTFOLDER=controllers
#   - TESTFOLDER=models
#   - TESTFOLDER=workers
#
# script: "bin/rspec spec/$TESTFOLDER"

script: "bin/rspec --format documentation"

addons:
  code_climate:
    repo_token: e129585ad0695fa1de512b276d7f7b8b79556e97aacb28469610568f3ed3bb1a
